Reorganizar ejemplos como Modulos
perujug/javaee8-jsonp pull request #6
Opened 2016-10-16 17:04 UTC by jeqo

Agregar repositorio de JSONP como sub-modulo Git, evitando configuraciones manuales de los demás developers en tener que descargar repositorio y compilarlo para tener dependencias locales.
Y, junto a esto, reorganizar ejemplos como modulos Maven para poder manejar las dependencias entre ejemplos y módulos de JSONP.

2016-10-31 15:51 UTC, eddumelendez requested changes
Thanks @jeqo I just add a minor change before to apply merge... Adding git submodule is great

2016-10-31 15:51 UTC, eddumelendez commented on json-pointer/json-pointer.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Looks like *.iml was ignored in .gitignore or the first commit was adding *.iml file and the next adding the extension to .gitignore file

2016-12-02 18:46 UTC, jeqo commented on json-pointer/json-pointer.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Should we keep IDE files outside the repo right? or should I remove it from .gitignore?

2016-12-02 19:43 UTC, jeqo commented
.iml removed

2016-12-03 21:24 UTC, closed without merging

2016-12-03 21:25 UTC, eddumelendez commented
Merged. Thanks @jeqo !